#
# ----------------------------
# Admin config's:
# 管理员配置项
# ----------------------------

# Custom name tag for each access level, where %s is the placeholder for the players name.
# Specify a comma separated list, starting with the tag for access level 1, or use "" to deactivate tags completely.
# Default:
# Access level 1 = [empty]
# Access level 2 = Junior Dev
# Access level 3 = Dev
# Access level 4 = Junior Event Master
# Access level 5 = Event Master
# Access level 6 = Junior Game Master
# Access level 7 = Game Master
# Access level 8 = Senior Game Master
# Access level 9 = Admin
# 每个访问级别的自定义名称标签，其中%s是玩家名称的占位符。
# 指定一个逗号分隔的列表，从访问级别1的标签开始，或使用""完全停用标签。
# 默认值：
# 访问级别1 = [空]
# 访问级别2 = 初级开发
# 访问级别3 = 开发
# 访问级别4 = 初级活动管理员
# 访问级别5 = 活动管理员
# 访问级别6 = 初级游戏管理员
# 访问级别7 = 游戏管理员
# 访问级别8 = 高级游戏管理员
# 访问级别9 = 管理员
# gameserver.administration.customtags = %s, \u00BBJDev\u00AB\uE04A%s, \u00BBDev\u00AB\uE04A%s, \u00BBJEM\u00AB\uE04A%s, \u00BBEM\u00AB\uE04A%s, \u00BBJGM\u00AB\uE04A%s, \u00BBGM\u00AB\uE04A%s, \u00BBSGM\u00AB\uE04A%s, \u00BBAdmin\u00AB\uE04A%s

# 自定义等级
# 访问级别1 = [空]
# 访问级别2 = vip 会员用户
# 访问级别3 = 高级会员用户
# 访问级别4 = 游戏管理员
# 访问级别5 = 开发者
# 访问级别6 = 超管
gameserver.administration.customtags = %s, \u00BBVip\u00AB\uE04A%s, \u00BBSuperVip\u00AB\uE04A%s, \u00BBGM\u00AB\uE04A%s, \u00BBAdmin\u00AB\uE04A%s

# ----------------------------
# Access config:
# 访问权限配置
# ----------------------------
# If the player has the given access level or higher, the option is active for him
# 如果玩家拥有给定或更高的访问级别，该选项对他激活

# Unrestricted item trades (restricted staff members can only trade items listed in item.restriction.txt to normal players)
# Default: 1
# 无限制物品交易（受限制的工作人员只能与普通玩家交易item.restriction.txt中列出的物品）
# 默认值：1
gameserver.administration.unrestricted_itemtrade = 1

# GM Panel
# Default: 2
# GM面板
# 默认值：2
gameserver.administration.gm_panel = 2

# GM skills
# Default: 8
# GM技能
# 默认值：8
gameserver.administration.gm_skills = 4

# Free Flight Everywhere
# Default: 1
# 随处自由飞行
# 默认值：1
gameserver.administration.flight.free_fly = 4

# Unlimited Flight Time for GM's
# Default: 1
# GM无限飞行时间
# 默认值：1
gameserver.administration.flight.unlimited_time = 3

# Resurrect anywhere without skill
# Default: 1
# 无需技能随时随地复活
# 默认值：1
gameserver.administration.auto_res = 3

# Can view player details, even when he denies it
# Default: 5
# 可以查看玩家详情，即使他拒绝
# 默认值：5
gameserver.administration.view_player_details = 4

# No instance requirements
# Default: 2
# 无副本进入要求
# 默认值：2
gameserver.administration.instance.enter_all = 3

# Open every door without using a key
# Default: 6
# 无需钥匙打开所有门
# 默认值：6
gameserver.administration.instance.open_doors = 4

# Show instance door info when clicking them
# Default: 9
# 点击副本门时显示信息
# 默认值：9
gameserver.administration.instance.door_info = 4

# Enter closed houses when clicking the door
# Default: 9
# 点击门时进入关闭的房屋
# 默认值：9
gameserver.administration.house.enter_all = 4

# Show house address when clicking the door
# Default: 9
# 点击门时显示房屋地址
# 默认值：9
gameserver.administration.house.show_address = 4

# Show additional information when clicking through dialog windows (quest ID, dialog action, ...)
# Default: 9
# 点击对话框时显示额外信息（任务ID、对话动作等）
# 默认值：9
gameserver.administration.dialog_info = 4

# Show success state/chance information when enchanting items
# Default: 9
# 强化物品时显示成功状态/几率信息
# 默认值：9
gameserver.administration.enchant_info = 3

# Show zone names when client notifies about passing one
# Default: 9
# 客户端通知穿过区域时显示区域名称
# 默认值：9
gameserver.administration.zone_info = 3

# Receive messages about possibly illegal player actions from AuditLogger
# Default: 9
# 接收来自审计记录器的可能非法玩家行为消息
# 默认值：9
gameserver.administration.audit_info = 4

# //quest command:
# Minimum access level to use parameters other than <reset> and <start>
# Default: 9
# //quest命令：
# 使用除<reset>和<start>以外参数的最低访问级别
# 默认值：9
gameserver.administration.command.quest.advanced_parameters = 3

# ----------------------------
# Connection options:
# 连接选项
# ----------------------------
# The following options are active for all staff members (access level > 0)
# 以下选项对所有工作人员（访问级别>0）激活

# Comma separated list of chat commands to execute on login
# 登录时执行的聊天命令的逗号分隔列表
# Default: //invis, //invul, //enemy none, //see
gameserver.administration.login.execute_commands = //see

# Minimum access level to see the server build date and revision on login (custom messages can be defined in events.xml via <login_message/>)
# Default: 9
# 登录时查看服务器构建日期和修订版本的最低访问级别（可通过events.xml中的<login_message/>定义自定义消息）
# 默认值：9
gameserver.administration.login.print_revision = 3

# Login announce levels
# 1,2,3 etc - announce only staff members with that access level ("" = off)
# Default: * (announce all of them)
# 登录公告级别
# 1,2,3等 - 仅公告具有该访问级别的工作人员（""=关闭）
# 默认值：*（公告所有）
gameserver.administration.login.announce_levels = ""

# GM login announce mode (false = announce only to other GMs with the specified levels)
# Default: true (announce to all players)
# GM登录公告模式（false=仅向指定级别的其他GM公告）
# 默认值：true（向所有玩家公告）
gameserver.administration.login.announce_to_all_players = false

# GM logout announce mode (false = announce only to other GMs with the specified levels)
# Default: true (announce to all players)
# GM登出公告模式（false=仅向指定级别的其他GM公告）
# 默认值：true（向所有玩家公告）
gameserver.administration.logout.announce_to_all_players = false