#
# ----------------------------
# Admin Commands:
# (depends on access level)
# ----------------------------
access = 4
add = 3
addcube = 3
addemotion = 4
addexp = 4
addset = 4
addskill = 4
addtitle = 4
ahserion = 4
ai = 5
alternpc = 4
announce = 3
announcements = 4
auction = 4
ban = 4
banchar = 4
banip = 4
banmac = 4
banhdd = 4
cinstance = 4
unbanmac = 4
base = 4
bk = 2
changerace = 4
collide = 4
configure = 5
cooldown = 4
coords = 1
damage = 4
debug = 5
delete = 4
delskill = 4
dispel = 4
dropinfo = 2
dye = 3
enemy = 3
energy = 4
equip = 4
event = 4
fixpath = 4
fsc = 4
gag = 4
group = 3
gameshop = 4
goto = 10
grant = 4
headhunting = 4
heal = 4
house = 4
html = 4
info = 3
instance = 4
invasion = 4
invis = 4
invul = 3
kick = 6
kill = 4
legion = 4
map = 4
megaphone = 4
worldraid = 4
morph = 4
motion = 4
moveto = 1
moveplayertoplayer = 4
movetome = 3
movie = 4
npcskill = 5
online = 1
passkeyreset = 5
pet = 3
playerinfo = 7
quest = 6
ranking = 5
relinquishcraft = 4
reload = 6
remove = 5
removecd = 4
rename = 4
res = 3
rift = 4
rprison = 4
say = 4
see = 1
send = 4
set = 4
siege = 4
spawn = 4
spawnu = 4
spawnAssembledNpc = 4
speed = 1
sprison = 4
stat = 4
state = 4
stoken = 4
sys = 4
sysmail = 4
teleportation = 4
time = 4
unban = 4
unbanchar = 4
unbanip = 4
useskill = 4
whisper = 1
weather = 4
whosyoudaddy = 3
zone = 4

# ----------------------------
# Player Commands:
# (depends on membership)
# ----------------------------
advent = 0
buy = 0
decompose = 0
del = 0
faction = 5
gmlist = 0
help = 0
id = 0
lock = 0
noexp = 0
nomorph = 0
preview = 0
pvp = 0
questrestart = 0

# event commands (levels will be overridden during event via <config_properties/> from events.xml)
easter = 5
symphony = 5

# ----------------------------
# Console Commands:
# (depends on access level)
# ----------------------------
Bookmark_add = 5
addcskill = 5
addquest = 5
attrbonus = 5
changeclass = 5
classup = 5
clearusercoolt = 5
combineskill = 5
delete_items = 5
deletecquest = 5
deleteskill = 5
endquest = 5
givetitle = 5
guild = 5
inventory = 5
invisible = 2
itemcooltime = 5
leveldown = 5
levelup = 5
partyrecall = 5
remove_skill_delay_all = 5
resurrect = 5
search = 5
set_enchantcount = 5
set_makeup_bonus = 5
set_vitalpoint = 5
setinventorygrowth = 5
skill = 5
status = 5
teleport = 5
teleport_to_named = 5
teleportto = 5
visible = 2
wish = 5
wishid = 5

# Location of chat command *.java handlers
gameserver.commands.handler_directories = ./data/handlers/admincommands, ./data/handlers/playercommands, ./data/handlers/consolecommands