#
# ----------------------------
# AI config's:
# AI 配置：
# ----------------------------

# Enable NPC movement
# 启用 NPC 移动
# Default: true
gameserver.npcmovement.enable = true

# The minimum time in seconds that the NPC waits before moving again.
# NPC 再次移动前等待的最短时间（秒）
# Default: 3 (seconds)
gameserver.npcmovement.delay.minimum = 3

# The maximum time in seconds that the NPC waits before moving again.
# NPC 再次移动前等待的最长时间（秒）
# Default: 15 (seconds)
gameserver.npcmovement.delay.maximum = 15

# Enable NPC shouts
# 启用 NPC 喊话
# Default: false
gameserver.npcshouts.enable = false

# Location of AI *.java handlers
# AI *.java 处理器的位置
gameserver.ai.handler_directory = ./data/handlers/ai

# ----------------------------
# AI debug (developer) config's:
# AI 调试（开发者）配置：
# ----------------------------

# Spawn AI NPCs with activated logging attribute
# 生成带有激活日志属性的 AI NPC
# Default: false
gameserver.ai.oncreate.debug = false

# Log movement for logging enabled NPCs
# 为启用日志的 NPC 记录移动情况
# Default: true
gameserver.ai.move.debug = true

# Save AI event log in NPC objects (can be retrieved via //ai2 command)
# 在 NPC 对象中保存 AI 事件日志（可通过 //ai2 命令获取）
# Default: false
gameserver.ai.event.debug = false