#
# ----------------------------
# AutoGroup config's:
# 自动组队配置：

# Enable Auto Group
# 启用自动组队
# Default: true
gameserver.autogroup.enable = true

# Enable check start time for pvp arenas
# 启用PVP竞技场的开始时间检查
# Default: true
gameserver.startTime.enable = true

# Dredgion registration period
# 深渊战舰注册周期
# Default: 60 min
gameserver.dredgion.registration_period = 60

# Dredgion start times
# 深渊战舰开始时间
# Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 逗号分隔的cron表达式列表（包含逗号的表达式必须用引号括起来）
# Default: "0 0 0,12,20 ? * *"
gameserver.dredgion.time = "0 0 0,12,14,16,18,20 ? * *"

# Kamar Battlefield registration period
# 卡玛尔战场注册周期
# Default: 60 min
gameserver.kamar_battlefield.registration_period = 60

# Kamar Battlefield start times
# 卡玛尔战场开始时间
# Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 逗号分隔的cron表达式列表（包含逗号的表达式必须用引号括起来）
# Default: "0 0 0,20 ? * MON,WED,SAT"
gameserver.kamar_battlefield.time = "0 0 0,20 ? * MON,WED,SAT"

# Engulfed Ophidan Bridge registration period
# 被淹没的蛇人桥注册周期
# Default: 60 min
gameserver.engulfed_ophidan_bridge.registration_period = 60

# Engulfed Ophidan Bridge registration start times
# 被淹没的蛇人桥注册开始时间
# Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 逗号分隔的cron表达式列表（包含逗号的表达式必须用引号括起来）
# Default: 0 0 12,19 ? * *
gameserver.engulfed_ophidan_bridge.time = "0 0 12,19 ? * *"

# Iron Wall Warfront registration period
# 铁壁前线注册周期
# Default: 60 min
gameserver.iron_wall_warfront.registration_period = 60

# Iron Wall Warfront registration start times
# 铁壁前线注册开始时间
# Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 逗号分隔的cron表达式列表（包含逗号的表达式必须用引号括起来）
# Default: "0 0 0,12 ? * SUN"
gameserver.iron_wall_warfront.time = "0 0 0,14,20 ? * SUN"

# Idgel Dome registration period
# 伊德盖尔圆顶注册周期
# Default: 60 min
gameserver.idgel_dome.registration_period = 60

# Idgel Dome registration start times
# 伊德盖尔圆顶注册开始时间
# Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 逗号分隔的cron表达式列表（包含逗号的表达式必须用引号括起来）
# Default: 0 0 23 ? * *
gameserver.idgel_dome.time = "0 0 0,14,20 ? * *"

# Announce battlefield registrations to the enemy faction
# 向敌对派系宣布战场注册
# Default: false
gameserver.autogroup.announce_battleground_registrations = true