#
# ----------------------------
# Database Cleaning config's:
# 数据库清理配置：
# ----------------------------

# Enable Database Cleaning
# 启用数据库清理
# Default: false
gameserver.cleaning.enable = false

# Minimum account inactivity in days, after which chars get deleted
# 账户不活跃的最小天数（超过这个天数的角色将被删除）
# Cleaning will only be executed with a value greater than 30
# 只有当值大于30时才会执行清理
# Default: 365
gameserver.cleaning.min_account_inactivity = 365

# Maximum level of characters that will be deleted on each account
# 每个账户上将要被删除的角色的最大等级
# Default: 25
gameserver.cleaning.max_level = 25