#
# ----------------------------
# Craft config's:
# 制作配置：
# ----------------------------

# Enable remove excess skills on player log in
# 启用在玩家登录时移除多余的技能
# Default: false
gameserver.craft.skills.delete.excess.enable = false

# Maximum number of expert skills a player can have
# 玩家可以拥有的专家技能的最大数量
# Default: 2
# Default: 2
gameserver.craft.max.expert.skills = 4

# Maximum number of master skills a player can have
# 玩家可以拥有的大师技能的最大数量
# Default: 1
gameserver.craft.max.master.skills = 4

# Enable leveling of aether and essence tapping skills above 499 points
# 启用将灵气和精华采集技能提升到499点以上
# Default: false
gameserver.craft.disable.tapping.cap = false

# 制作失败的几率
gameserver.craft.fail.chance = 50

# 采集失败的几率
gameserver.gather.fail.chance = 50