#
# ----------------------------
# Drop config's:
# 掉落配置：
# ----------------------------

# Announce when a player drops an item with the given minimum item quality (or higher). Leave empty to disable drop announces
# 当玩家掉落具有给定最低物品品质（或更高）的物品时进行公告。留空以禁用掉落公告
# Possible values: JUNK, COMMON, RARE, LEGEND, UNIQUE, EPIC or MYTHIC
# 可能的值: JUNK, COMMON, RARE, LEGEND, UNIQUE, EPIC 或 MYTHIC
# Default: MYTHIC
gameserver.drop.announce_quality = MYTHIC

# Comma separated list of map ids where team members can roll for drops anywhere on the map instead of in the default range
# 以逗号分隔的地图ID列表，在这些地图中，团队成员可以在地图的任何地方而不是默认范围内为掉落物进行掷骰
# Default:
gameserver.drop.disable_range_check_maps =