#
# ----------------------------
# Event config's:
# 事件配置：
# ----------------------------
# Disabled Events (insert comma separated names from timed_events or * for all)
# 禁用的事件（从timed_events中插入逗号分隔的名称或用*表示全部）
# Start and end times for events are set in timed_events (no start and end time means permanently active)
# 事件的开始和结束时间在timed_events中设置（没有开始和结束时间意味着永久激活）
# Default: empty string (none)
# Default: 空字符串（无）
gameserver.event.service.disabled_events = 

# ----------------------------
# Event Upgrade Arcade:
# 事件升级街机：
# ----------------------------
# Enable Upgrade Arcade
# 启用升级街机
# Default: false
gameserver.event.arcade.enable = true

# Upgrade Arcade tokens needed to resume
# 升级街机继续游戏所需的代币数量
# Default: 3
gameserver.event.arcade.resume_token = 3

# ----------------------------
# Invasion / World Raids:
# 入侵/世界突袭：
# ----------------------------
# Enable World Raids - Default: true
# 启用世界突袭 - Default: true
gameserver.worldraid.enable = true

# Enable World Raid spawn message - Default: true
# 启用世界突袭生成消息 - Default: true
gameserver.worldraid.use_spawn_msg = true

# ----------------------------
# Headhunting:
# 猎头行动：
# ----------------------------
# Enable Headhunting
# 启用猎头行动
# Default: false
gameserver.event.headhunting.enable = false

# Headhunting allowed maps (f.e. 600090000,600100000)
# 猎头行动允许的地图（例如：600090000,600100000）
# Default: 
gameserver.event.headhunting.maps = 

# Headhunting needed kills to receive the consolation prize
# 获得安慰奖所需的猎头行动击杀数量
# Default: 50
gameserver.event.headhunting.consolation_prize_kills = 50