#
# ----------------------------
# Geodata config's:
# ----------------------------
# 地理数据配置

# Enable Geodata (heights and meshes)
# Default: true
# 启用地理数据(高度和网格)
# 默认值: true
gameserver.geodata.enable = true

# Enable canSee checks using geodata.
# Default: true
# 启用基于地理数据的视线检查
# 默认值: true
gameserver.geodata.cansee.enable = true

# Enable fear skill using geodata.
# Default: true
# 启用基于地理数据的恐惧技能
# 默认值: true
gameserver.geodata.fear.enable = true

# If enabled - during movements npcs will be checking z coordinate based on geo if target is flying
# Default: true
# 若启用，NPC在移动时会基于地理数据检查飞行目标的z坐标
# 默认值: true
gameserver.geodata.npc.move = true

#Enable geo materials using skills
# Default: true
# 启用基于地理数据的技能材料系统
# 默认值: true
gameserver.geodata.materials.enable = true

# Show collision zone name and skill id for GMs
# Default: false
# 为GM显示碰撞区域名称和技能ID
# 默认值: false
gameserver.geodata.materials.showdetails = false

# Enable geodata shields
# Default: true
# 启用地理数据护盾
# 默认值: true
gameserver.geodata.shields.enable = true