#
# ----------------------------
# HTML config's:
# HTML配置项：
# ----------------------------

# Enable HTML welcome message
# 启用HTML欢迎消息
# Default: false
gameserver.html.welcome.enable = true

# Enable HTML Guides system
# 启用HTML指南系统
# Default: false
gameserver.html.guides.enable = true

# Html files directory
# HTML文件目录
# Default: ./data/static_data/HTML/
gameserver.html.root = ./data/static_data/HTML/

# Html cache directory
# HTML缓存目录
# Default: ./cache/html.cache
gameserver.html.cache.file = ./cache/html.cache

# Encoding
# 编码设置
# Default: UTF-8
gameserver.html.encoding = UTF-8