#
# ----------------------------
# In game shop config's:
# ----------------------------
# Don't forget add on launcher -ingameshop

# Enable in game shop
# 启用游戏内商店
# Default: false
gameserver.ingameshop.enable = true

# Enable gift system between factions
# 允许在游戏中进行礼物系统
# Default: false
gameserver.ingameshop.gift = true

# allows gifts at all or no
# 允许在游戏中进行礼物系统
gameserver.ingameshop.allow.gift = true
