#

# Send server errors and warnings to a Discord channel (see logback.xml for further configuration)
# 将服务器错误和警告发送到Discord频道（参见logback.xml进行进一步配置）
# Default: empty (deactivated)
gameserver.log.status.discord.webhook_url =
# The avatar url is inserted in the conversion pattern in logback.xml and therefore can use Logback variables, such as %level (see
# 头像URL插入到logback.xml的转换模式中，因此可以使用Logback变量，如%level（参见
# http://logback.qos.ch/manual/layouts.html#conversionWord) to set different avatars depending on the severity.
# http://logback.qos.ch/manual/layouts.html#conversionWord）根据严重性设置不同的头像。
gameserver.log.status.discord.avatar_url =

# Enable audit logging
# 启用审计日志
# Default: true
gameserver.log.audit = true

# Enable craft logging
# 启用制作日志
# Default: true
gameserver.log.craft = false

# Enable player exchange logging
# 启用玩家交易日志
# Default: false
gameserver.log.player.exchange = false

# Enable Broker exchange logging
# 启用交易所交易日志
# Default: false
gameserver.log.broker.exchange = false

# Enable gameshop logging
# 启用游戏商城日志
# Default: false
gameserver.log.ingameshop = false

# Enable gameshop logging into database
# 启用游戏商城数据库日志
# Default: false
gameserver.log.ingameshop.sql = false

# Enable gmaudit logging (chat commands, gm whispers, ...)
# 启用GM审计日志（聊天命令、GM私聊等）
# Default: true
gameserver.log.gmaudit = true

# Enable general chat logging (public, group, shout, ...)
# 启用一般聊天日志（公共、组队、喊话等）
# Default: true
gameserver.log.chats.general = true

# Enable private chat logging (legion & whisper)
# 启用私人聊天日志（军团和私聊）
# Default: false
gameserver.log.chats.private = false

# Enable item logging
# 启用物品日志
# Default: true
gameserver.log.item = true

# Enable kill logging
# 启用击杀日志
# Default: false
gameserver.log.kill = false

# Enable PowerLeveling logging
# 启用代练日志
# Default: false
gameserver.log.pl = false

# Enable mail logging
# 启用邮件日志
# Default: false
gameserver.log.mail = false

# Enable siege logging
# 启用攻城战日志
# Default: false
gameserver.log.siege = false

# Enable sysmail logging
# 启用系统邮件日志
# Default: false
gameserver.log.sysmail = false

# Enable house auction result logging
# 启用房屋拍卖结果日志
# Default: true
gameserver.log.auction = true

# Enable tampering log
# 启用篡改日志
# Default: false
gameserver.log.tampering = false