#
# ----------------------------
# Membership config's:
# 会员系统配置
# ----------------------------
#
# Options in this file are enabled for players with the given membership level or above.
# 0 means regular players, since it's the default membership of new players
# 1 means players with membership level 1 and so on
# 此文件中的选项对具有指定会员等级或更高级别的玩家启用
# 0表示普通玩家（新玩家的默认会员等级）
# 1表示1级会员，以此类推

# Comma separated membership names for notification on login, starting with the name for membership 1
# Default: Premium
# 登录通知中使用的会员名称（逗号分隔），从1级会员名称开始
gameserver.membership.types = 普通, 高级会员, 超级会员

# Allow gathering while riding a mount
# Default: 10
# 允许在骑乘坐骑时进行采集
gameserver.membership.gathering.allow_on_mount = 3

# Disable instances title requirement
# Default: 10
# 禁用副本头衔要求
gameserver.instances.title.requirement = 4

# Disable instances race requirement
# Default: 10
# 禁用副本种族要求
gameserver.instances.race.requirement = 4

# Disable instances level requirement
# Default: 10
# 禁用副本等级要求
gameserver.instances.level.requirement = 4

# Disable instances group requirement
# Default: 10
# 禁用副本队伍要求
gameserver.instances.group.requirement = 2

# Disable instances quest requirement
# Default: 10
# 禁用副本任务要求
gameserver.instances.quest.requirement = 3

# Decrease instances cooldowns
# Default: 10
# 减少副本冷却时间
gameserver.instances.cooldown = 3

# All emotions available
# Default: 10
# 解锁所有表情动作
gameserver.emotions.all = 2

# Not require quest for normal/advanced stigma slots
# Default: 10
# 普通/高级圣痕槽不需要完成任务
gameserver.quest.stigma.slot = 4

# Disable soulsickness (debuf after death)
# Default: 10
# 禁用灵魂疾病（死亡后的减益效果）
gameserver.soulsickness.disable = 3

# Enable stigma auto learn mode
# Default: 10
# 启用圣痕自动学习模式
gameserver.autolearn.stigma = 4

# Disable quest limit
# Default: 10
# 禁用任务数量限制
gameserver.quest.limit.disable = 2

# Enable additional count of characters per account
# Default: 10
# 允许每个账户创建额外数量的角色
gameserver.character.additional.enable = 4

# ----------------------------
# Membership Options:
# 会员选项详情
# ----------------------------
# Count of characters for this membership (max 8)
# Default: 8
# 此会员等级可创建的角色数量（最多8个）
gameserver.character.additional.count = 2