#
# ----------------------------
# Name config's:
# ----------------------------

# If enabled, players will be able to create chars or adopt pets with not retail like names (first letter uppercase, rest lowercase)
# Default: false
gameserver.name.allow.custom = false

# Character name pattern to be checked at char creation and rename
# To enable UTF support for names - set this parameter to [a-zA-Z\u0410-\u042f\u0430-\u044f]{2,16}
# Default: [a-zA-Z]{2,16}
# 修改为允许中文、英文和俄文字符
gameserver.name.character_pattern = [a-zA-Z\u4e00-\u9fa5\u0410-\u042f\u0430-\u044f]{2,16}

# Pet name pattern to be checked on pet adoption and rename
# To enable UTF support for names - set this parameter to [a-zA-Z\u0410-\u042f\u0430-\u044f]{2,16}
# Default: [a-zA-Z]{2,16}
# 同样修改宠物名称模式以允许中文
gameserver.name.pet_pattern = [a-zA-Z\u4e00-\u9fa5\u0410-\u042f\u0430-\u044f]{2,16}

# Forbidden string sequence pattern in names.
# Filters names (chars, legions, pets)
# Default: empty string
gameserver.name.forbidden_sequences_pattern = 

# Comma separated list of forbidden words (current words are parsed from aion 4.7 client).
# Filters names (chars, legions, pets) & chat
# Default: empty string
gameserver.name.forbidden_words = development

# Number of days a name is reserved after renaming. During this time, only the renamed player can (re)adopt this name.
gameserver.name.reserve_old_name_days = 30