#
# ----------------------------
# Periodic save intervals:
# 定期保存间隔：
# ----------------------------
# WARNING:
# 警告：
# With 500 player online saving can be up to 10 seconds
# 500名玩家在线时，保存过程可能长达10秒
# (it depends on hardware, changes in item locations, new acquisitions etc)
# （取决于硬件、物品位置变化、新获得物品等因素）
# Generally accepted interval is 15-20 minutes.
# 普遍接受的间隔为15-20分钟。

# Time in seconds for saving player data (player, abyss rank, quests, skills)
# 保存玩家数据的时间间隔（秒）（玩家、深渊排名、任务、技能）
# Default: 900 (15 minutes)
gameserver.periodicsave.player.general = 900

# Time in seconds for saving player items and item stones
# 保存玩家物品和物品石的时间间隔（秒）
# Default: 900 (15 minutes)
gameserver.periodicsave.player.items = 900

# Time in seconds for saving legion wh items and item stones
# 保存军团仓库物品和物品石的时间间隔（秒）
# Default: 1200 (20 minutes)
gameserver.periodicsave.legion.items = 1200

# Time in seconds for saving/updating pet mood data
# 保存/更新宠物心情数据的时间间隔（秒）
# Default: 10
gameserver.periodicsave.player.pets = 10
