#
# ----------------------------
# Prices config's:
# 价格配置项：
# ----------------------------

# Controls the "Prices:" value in influence tab
# 控制影响力标签中的"价格"值
# Default: 100
gameserver.prices.default.prices = 100

# Hidden modifier for all prices
# 所有价格的隐藏修改器
# Default: 100
gameserver.prices.default.modifier = 100

# Taxes: value = 100 + tax %
# 税收：值 = 100 + 税率%
# Default: 100
gameserver.prices.default.taxes = 100

# Default: 100
# 默认值：100
gameserver.prices.vendor.buymod = 100

# Default: 20
# 默认值：20
gameserver.prices.vendor.sellmod = 20