#
# ----------------------------
# Punishment config's:
# 惩罚系统配置项：
# ----------------------------

# Enable auto punishment
# 启用自动惩罚
# Default: false
gameserver.punishment.enable = false

# Punishment type
# 惩罚类型
# 1 - kick
# 1 - 踢出游戏
# 2 - ban character
# 2 - 封禁角色
# 3 - ban account
# 3 - 封禁账号
# 4 - ban ip
# 4 - 封禁IP
# 5 - ban mac
# 5 - 封禁MAC地址
# Default: 1
gameserver.punishment.type = 1

# Punishment time in minutes
# 惩罚时间（分钟）
# Default: 1440 (1 day)
gameserver.punishment.time = 1440