#
# ----------------------------
# Thread config's:
# ----------------------------

# Number of threads that are dedicated to handle instant tasks.
# A value of 0 means auto. On auto, the number is usually equal to the number of logical CPU cores as reported by Runtime#availableProcessors(), but
# never less than four.
# 用于处理即时任务的线程数量。
# 值为0表示自动配置。在自动模式下，线程数量通常等于Runtime#availableProcessors()报告的逻辑CPU核心数，
# 但不少于4个。
# Default: 0
gameserver.thread.base_pool_size = 0

# Number of threads that are dedicated to handle scheduled tasks.
# A value of 0 means auto. On auto, the number is usually equal to the number of logical CPU cores as reported by Runtime#availableProcessors(), but
# never less than four.
# 用于处理计划任务的线程数量。
# 值为0表示自动配置。在自动模式下，线程数量通常等于Runtime#availableProcessors()报告的逻辑CPU核心数，
# 但不少于4个。
# Default: 0
gameserver.thread.scheduled_pool_size = 0

# Logs a warning if any thread needs longer than this time to finish a task. Time in milliseconds.
# 记录警告日志，如果任何线程需要超过此时间完成任务。时间单位为毫秒。
# Default: 5000
gameserver.thread.runtime = 5000

# Use higher thread priorities for instant thread pool
# Note: in Linux you must be root and use switches: -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=1
# 为即时线程池使用较高的线程优先级
# 注意：在Linux中，您必须以root用户身份运行并使用开关：-XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=1
# Default: false
gameserver.thread.usepriority = false
